# Generated by Django 3.2.8 on 2021-10-09 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomE', models.CharField(max_length=20)),
                ('TelephoneE', models.IntegerField()),
                ('AdresseE', models.CharField(max_length=50)),
                ('DescriptionE', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_De_Camion', models.IntegerField(choices=[(1, 'Break'), (2, 'Forgon'), (3, 'Camoin 20m'), (4, 'Camion Poid Lourd'), (5, 'Porteur')], default=0)),
                ('Date_De_Debut_De_Reservation', models.DateField()),
                ('Date_De_Fin_De_Reservation', models.DateField()),
                ('Nom_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Reseve_Par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprise')),
            ],
        ),
    ]
