# Generated by Django 3.2.8 on 2021-10-09 20:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprise', '0002_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='reservation',
            index_together={('Reseve_Par', 'Nom_Client')},
        ),
    ]
