# Generated by Django 3.2.8 on 2021-10-09 20:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprise', '0003_auto_20211009_2222'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('Reseve_Par', 'Nom_Client')},
        ),
    ]
