# Generated by Django 3.2.8 on 2021-10-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='reservation',
            index_together=set(),
        ),
    ]
