# Generated by Django 3.2.8 on 2021-10-10 19:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprise', '0006_alter_reservation_index_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('Reseve_Par', 'Nom_Client')},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Date_De_Debut_De_Reservation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Date_De_Fin_De_Reservation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Type_De_Camion',
        ),
    ]
