# Generated by Django 3.2.8 on 2021-10-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_auto_20211010_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Type_De_Camion',
            field=models.IntegerField(default=0),
        ),
    ]
