# Generated by Django 3.2.8 on 2021-10-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_reservation_type_de_camion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
    ]
