# Generated by Django 3.2.8 on 2021-10-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0010_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Type_De_Camion',
            field=models.IntegerField(choices=[(1, 'Break'), (2, 'forgon'), (3, 'Poid lourd')]),
        ),
    ]
