# Generated by Django 3.2.8 on 2021-10-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0011_alter_reservation_type_de_camion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Type_De_Camion',
            field=models.IntegerField(default=0),
        ),
    ]
