# Generated by Django 3.2.8 on 2021-10-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cient',
            new_name='Client',
        ),
    ]
