# Generated by Django 3.2.8 on 2021-10-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation',
            new_name='ReservationClient',
        ),
        migrations.AddField(
            model_name='reservation',
            name='TypeDeCamion',
            field=models.IntegerField(choices=[(1, 'Break'), (2, 'Forgon'), (3, 'Camoin 20m'), (4, 'Camion Poid Lourd'), (5, 'Porteur')], default=1),
        ),
    ]
