# Generated by Django 3.2.8 on 2021-10-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20211007_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='TypeDeCamion',
            field=models.IntegerField(choices=[(1, 'Break'), (2, 'Forgon'), (3, 'Camoin 20m'), (4, 'Camion Poid Lourd'), (5, 'Porteur')], default=0),
        ),
    ]
