# Generated by Django 3.2.8 on 2021-10-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20211007_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='DateDeNaissance',
            field=models.DateField(null=True),
        ),
    ]
