# Generated by Django 3.2.8 on 2021-10-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_remove_client_datedenaissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='DateDeNaissance',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
    ]
