# Generated by Django 3.2.8 on 2021-10-07 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_remove_client_datedenaissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='DateDeNaissance',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
