# Generated by Django 3.2.8 on 2021-10-07 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_remove_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='DateDeNaissance',
            field=models.DateField(default='2021-10-01.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
