# Generated by Django 3.2.8 on 2021-10-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20211007_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='DateDeNaissance',
        ),
    ]
