# Generated by Django 3.2.8 on 2021-10-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_remove_client_datedenaissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
