# Generated by Django 3.2.8 on 2021-10-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
