# Generated by Django 3.2.8 on 2021-10-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_client_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Date',
        ),
    ]
