# Generated by Django 3.2.8 on 2021-10-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_remove_client_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='DateDeNaissance',
            field=models.DateField(blank=True, default='2021-10-02'),
        ),
    ]
