# Generated by Django 3.2.8 on 2021-10-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_remove_client_datedenaissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='DateDeNaissance',
            field=models.DateField(blank=True, default=1955),
            preserve_default=False,
        ),
    ]
