# Generated by Django 3.2.8 on 2021-10-08 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_remove_client_datedenaissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='DateDeNaissance',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
