# Generated by Django 3.2.8 on 2021-10-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_remove_client_datedenaissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='DateDeNaissance',
            field=models.DateTimeField(default=2001),
            preserve_default=False,
        ),
    ]
