# Generated by Django 3.2.8 on 2021-10-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0036_auto_20211008_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='DateDeNaissance',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
