# Generated by Django 3.2.8 on 2021-10-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0039_auto_20211008_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='DateDeNaissance',
            field=models.DateField(auto_now_add=True),
        ),
    ]
